/**
 * One icon family for the whole product (Phosphor, regular weight by default). Components import from here,
 * never from the icon package directly, so the family and weight stay consistent everywhere.
 * Names are the product's own vocabulary (kept from the earlier icon set to avoid churn in every page).
 */
import React from 'react';
import * as P from '@phosphor-icons/react';

type Props = React.SVGProps<SVGSVGElement> & { weight?: P.IconWeight; size?: number | string };
const wrap = (Icon: P.Icon, defaultWeight: P.IconWeight = 'regular') => {
  const C = React.forwardRef<SVGSVGElement, Props>(({ weight, ...rest }, ref) =>
    <Icon ref={ref} weight={weight ?? defaultWeight} aria-hidden={rest['aria-label'] ? undefined : true} {...(rest as any)} />);
  C.displayName = Icon.displayName;
  return C;
};

export const Activity = wrap(P.Pulse);
export const AlertCircle = wrap(P.WarningCircle);
export const AlertOctagon = wrap(P.WarningOctagon);
export const AlertTriangle = wrap(P.Warning);
export const ArrowDownRight = wrap(P.ArrowDownRight);
export const ArrowRight = wrap(P.ArrowRight);
export const ArrowUpRight = wrap(P.ArrowUpRight);
export const BarChart3 = wrap(P.ChartBar);
export const Bell = wrap(P.Bell);
export const BellRing = wrap(P.BellRinging);
export const Box = wrap(P.Cube);
export const Brain = wrap(P.Brain);
export const Building2 = wrap(P.Buildings);
export const CalendarClock = wrap(P.CalendarCheck);
export const Camera = wrap(P.Camera);
export const Check = wrap(P.Check, 'bold');
export const CheckCircle2 = wrap(P.CheckCircle);
export const ChevronDown = wrap(P.CaretDown);
export const ChevronRight = wrap(P.CaretRight);
export const CircleDot = wrap(P.CircleDashed);
export const ClipboardCheck = wrap(P.SealCheck);
export const Clock = wrap(P.Clock);
export const CloudOff = wrap(P.CloudSlash);
export const CloudRain = wrap(P.CloudRain);
export const Command = wrap(P.Command);
export const Cpu = wrap(P.ChartPieSlice);
export const Crosshair = wrap(P.Crosshair);
export const Database = wrap(P.Database);
export const Download = wrap(P.DownloadSimple);
export const Droplets = wrap(P.Drop);
export const ExternalLink = wrap(P.ArrowSquareOut);
export const FileImage = wrap(P.FileImage);
export const FileSpreadsheet = wrap(P.FileCsv);
export const FlaskConical = wrap(P.Flask);
export const Globe2 = wrap(P.Globe);
export const Info = wrap(P.Info);
export const KeyRound = wrap(P.Key);
export const Layers = wrap(P.Stack);
export const LayoutDashboard = wrap(P.SquaresFour);
export const Link2 = wrap(P.LinkSimple);
export const Loader2 = wrap(P.CircleNotch, 'bold');
export const LocateFixed = wrap(P.GpsFix);
export const Lock = wrap(P.Lock);
export const LogOut = wrap(P.SignOut);
export const Mail = wrap(P.Envelope);
export const Map = wrap(P.MapTrifold);
export const MapPin = wrap(P.MapPin);
export const MessageSquareWarning = wrap(P.ChatTeardropText);
export const Mic = wrap(P.Microphone);
export const MicOff = wrap(P.MicrophoneSlash);
export const Minus = wrap(P.Minus);
export const Navigation = wrap(P.NavigationArrow);
export const Newspaper = wrap(P.Newspaper);
export const PenLine = wrap(P.PenNib);
export const Pencil = wrap(P.PencilSimple);
export const PencilLine = wrap(P.PencilLine);
export const Phone = wrap(P.Phone);
export const Plus = wrap(P.Plus);
export const Radio = wrap(P.Broadcast);
export const RadioTower = wrap(P.CellTower);
export const RefreshCw = wrap(P.ArrowsClockwise);
export const RotateCcw = wrap(P.ArrowCounterClockwise);
export const Route = wrap(P.Path);
export const Satellite = wrap(P.GpsFix);
export const Save = wrap(P.FloppyDisk);
export const Scale = wrap(P.Scales);
export const Search = wrap(P.MagnifyingGlass);
export const SearchCheck = wrap(P.SealCheck);
export const Send = wrap(P.PaperPlaneTilt);
export const Settings2 = wrap(P.SlidersHorizontal);
export const ShieldCheck = wrap(P.ShieldCheck);
export const Sigma = wrap(P.Sigma);
export const SignalLow = wrap(P.CellSignalLow);
export const Sparkles = wrap(P.Sparkle);
export const Square = wrap(P.Square, 'fill');
export const Ticket = wrap(P.Ticket);
export const Trash2 = wrap(P.Trash);
export const Truck = wrap(P.Truck);
export const Volume2 = wrap(P.SpeakerHigh);
export const VolumeX = wrap(P.SpeakerSlash);
export const Warehouse = wrap(P.Warehouse);
export const WifiOff = wrap(P.WifiSlash);
export const Wrench = wrap(P.Wrench);
export const X = wrap(P.X);
export const XCircle = wrap(P.XCircle);
// additions for the redesign
export const Sun = wrap(P.Sun);
export const Moon = wrap(P.Moon);
export const Monitor = wrap(P.Monitor);
export const CaretUpDown = wrap(P.CaretUpDown);
export const CaretUp = wrap(P.CaretUp);
export const CaretLeft = wrap(P.CaretLeft);
export const Funnel = wrap(P.Funnel);
export const ArrowsOut = wrap(P.ArrowsOut);
export const Gauge = wrap(P.Gauge);
export const Timer = wrap(P.Timer);
export const Compass = wrap(P.Compass);
export const Eye = wrap(P.Eye);
export const EyeSlash = wrap(P.EyeSlash);
export const ListBullets = wrap(P.ListBullets);
export const DotsThree = wrap(P.DotsThree);
export const Waves = wrap(P.Waves);
export const Faders = wrap(P.Faders);
export const Lightning = wrap(P.Lightning);
export const HandTap = wrap(P.HandTap);
export const Fingerprint = wrap(P.Fingerprint);
