"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 16:33:37.036087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)

    op.create_table('communities',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('ward', sa.String(length=80), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('daily_demand', sa.Integer(), nullable=False),
    sa.Column('allocated_water', sa.Integer(), nullable=False),
    sa.Column('previous_allocation', sa.Integer(), nullable=False),
    sa.Column('vulnerability_score', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('contact_officer', sa.String(length=120), nullable=False),
    sa.Column('officer_phone', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_communities'))
    )
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_communities_name'), ['name'], unique=False)

    op.create_table('depots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depots'))
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('ward', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('allocation_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_supply', sa.Integer(), nullable=False),
    sa.Column('total_demand', sa.Integer(), nullable=False),
    sa.Column('fairness_before', sa.Float(), nullable=False),
    sa.Column('fairness_after', sa.Float(), nullable=False),
    sa.Column('weights', sa.JSON(), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('demand_source', sa.String(length=40), nullable=False),
    sa.Column('disruption', sa.JSON(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_allocation_plans_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_plans'))
    )
    with op.batch_alter_table('allocation_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_plans_created_at'), ['created_at'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('category_confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('severity_confidence', sa.Float(), nullable=False),
    sa.Column('sentiment', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_officer', sa.String(length=120), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('duplicate_probability', sa.Float(), nullable=False),
    sa.Column('similar_count', sa.Integer(), nullable=False),
    sa.Column('recommended_action', sa.Text(), nullable=False),
    sa.Column('predicted_category', sa.String(length=40), nullable=False),
    sa.Column('predicted_severity', sa.String(length=16), nullable=False),
    sa.Column('label_verified', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('reporter_name', sa.String(length=120), nullable=False),
    sa.Column('reporter_phone', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_complaints_community_id_communities')),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['complaints.id'], name=op.f('fk_complaints_duplicate_of_id_complaints')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_complaints'))
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaints_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)

    op.create_table('demand_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('litres', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_demand_observations_community_id_communities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_observations')),
    sa.UniqueConstraint('community_id', 'date', name=op.f('uq_demand_observations_community_id'))
    )
    with op.batch_alter_table('demand_observations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_demand_observations_community_id'), ['community_id'], unique=False)

    op.create_table('tankers',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('vehicle_number', sa.String(length=20), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('driver_user_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(length=120), nullable=False),
    sa.Column('driver_phone', sa.String(length=32), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('current_load', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('last_ping_at', sa.DateTime(), nullable=True),
    sa.Column('breakdown_note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], name=op.f('fk_tankers_depot_id_depots')),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name=op.f('fk_tankers_driver_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tankers')),
    sa.UniqueConstraint('vehicle_number', name=op.f('uq_tankers_vehicle_number'))
    )
    op.create_table('water_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('requested_amount', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('people_currently_served', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('days_without_water', sa.Integer(), nullable=False),
    sa.Column('contact_person', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('assessment', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_water_requests_community_id_communities')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_water_requests_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_requests'))
    )
    with op.batch_alter_table('water_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_water_requests_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_requests_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_water_requests_status'), ['status'], unique=False)

    op.create_table('allocation_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('demand', sa.Integer(), nullable=False),
    sa.Column('previous_allocation', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('survival_floor', sa.Integer(), nullable=False),
    sa.Column('recommended', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_allocation_items_community_id_communities')),
    sa.ForeignKeyConstraint(['plan_id'], ['allocation_plans.id'], name=op.f('fk_allocation_items_plan_id_allocation_plans')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_allocation_items'))
    )
    with op.batch_alter_table('allocation_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allocation_items_plan_id'), ['plan_id'], unique=False)

    op.create_table('gps_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanker_id', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmh', sa.Float(), nullable=False),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], name=op.f('fk_gps_pings_tanker_id_tankers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gps_pings'))
    )
    with op.batch_alter_table('gps_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gps_pings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gps_pings_tanker_id'), ['tanker_id'], unique=False)

    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tanker_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('route_geometry', sa.JSON(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=False),
    sa.Column('duration_min', sa.Float(), nullable=False),
    sa.Column('baseline_distance_km', sa.Float(), nullable=False),
    sa.Column('baseline_duration_min', sa.Float(), nullable=False),
    sa.Column('routing_source', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_trips_created_by_users')),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], name=op.f('fk_trips_tanker_id_tankers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trips'))
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_tanker_id'), ['tanker_id'], unique=False)

    op.create_table('trip_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('allocated_litres', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_trip_stops_community_id_communities')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_trip_stops_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_trip_stops'))
    )
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_stops_trip_id'), ['trip_id'], unique=False)

    op.create_table('deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_stop_id', sa.Integer(), nullable=True),
    sa.Column('tanker_id', sa.String(length=20), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('allocated_amount', sa.Integer(), nullable=False),
    sa.Column('delivered_amount', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('geofence_distance_m', sa.Float(), nullable=True),
    sa.Column('gps_verified', sa.Boolean(), nullable=False),
    sa.Column('officer_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('variance_amount', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('photo_path', sa.String(length=255), nullable=True),
    sa.Column('trip_minutes', sa.Float(), nullable=True),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_deliveries_community_id_communities')),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], name=op.f('fk_deliveries_tanker_id_tankers')),
    sa.ForeignKeyConstraint(['trip_stop_id'], ['trip_stops.id'], name=op.f('fk_deliveries_trip_stop_id_trip_stops')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_deliveries'))
    )
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_deliveries_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_delivered_at'), ['delivered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_deliveries_tanker_id'), ['tanker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_deliveries_tanker_id'))
        batch_op.drop_index(batch_op.f('ix_deliveries_delivered_at'))
        batch_op.drop_index(batch_op.f('ix_deliveries_community_id'))

    op.drop_table('deliveries')
    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_stops_trip_id'))

    op.drop_table('trip_stops')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trips_tanker_id'))
        batch_op.drop_index(batch_op.f('ix_trips_status'))

    op.drop_table('trips')
    with op.batch_alter_table('gps_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gps_pings_tanker_id'))
        batch_op.drop_index(batch_op.f('ix_gps_pings_recorded_at'))

    op.drop_table('gps_pings')
    with op.batch_alter_table('allocation_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_items_plan_id'))

    op.drop_table('allocation_items')
    with op.batch_alter_table('water_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_water_requests_status'))
        batch_op.drop_index(batch_op.f('ix_water_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_water_requests_community_id'))

    op.drop_table('water_requests')
    op.drop_table('tankers')
    with op.batch_alter_table('demand_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_demand_observations_community_id'))

    op.drop_table('demand_observations')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_community_id'))

    op.drop_table('complaints')
    with op.batch_alter_table('allocation_plans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allocation_plans_created_at'))

    op.drop_table('allocation_plans')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('depots')
    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_communities_name'))

    op.drop_table('communities')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
