"""trip lifecycle telemetry disasters geography provenance

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-02 16:33:39.135830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('key', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_data_sources'))
    )
    op.create_table('disaster_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('polygon_url', sa.String(length=500), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('event_raw', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('urgency', sa.String(length=16), nullable=False),
    sa.Column('certainty', sa.String(length=16), nullable=False),
    sa.Column('msg_type', sa.String(length=16), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('area_desc', sa.Text(), nullable=False),
    sa.Column('lgd_district_codes', sa.JSON(), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('geometry_status', sa.String(length=16), nullable=False),
    sa.Column('effective_at', sa.DateTime(), nullable=True),
    sa.Column('onset_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('raw', sa.Text(), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_disaster_events')),
    sa.UniqueConstraint('external_id', name=op.f('uq_disaster_events_external_id'))
    )
    with op.batch_alter_table('disaster_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_disaster_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_events_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_disaster_events_source'), ['source'], unique=False)

    op.create_table('geo_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lgd_code', sa.String(length=16), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_states')),
    sa.UniqueConstraint('external_id', name=op.f('uq_geo_states_external_id')),
    sa.UniqueConstraint('lgd_code', name=op.f('uq_geo_states_lgd_code'))
    )
    with op.batch_alter_table('geo_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_states_name'), ['name'], unique=False)

    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('created', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('unchanged', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_runs'))
    )
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestion_runs_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_ingestion_runs_started_at'), ['started_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('entity', sa.String(length=40), nullable=False),
    sa.Column('entity_id', sa.String(length=40), nullable=False),
    sa.Column('dedupe_key', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_notifications_dedupe_key'))
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)

    op.create_table('geo_districts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('lgd_code', sa.String(length=16), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('centroid_lat', sa.Float(), nullable=True),
    sa.Column('centroid_lng', sa.Float(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.Column('license', sa.String(length=200), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['state_id'], ['geo_states.id'], name=op.f('fk_geo_districts_state_id_geo_states')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_geo_districts')),
    sa.UniqueConstraint('external_id', name=op.f('uq_geo_districts_external_id'))
    )
    with op.batch_alter_table('geo_districts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_districts_lgd_code'), ['lgd_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_districts_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_geo_districts_state_id'), ['state_id'], unique=False)

    op.create_table('notification_reads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_reads_notification_id_notifications')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_reads_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_reads')),
    sa.UniqueConstraint('notification_id', 'user_id', name=op.f('uq_notification_reads_notification_id'))
    )
    with op.batch_alter_table('notification_reads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_reads_notification_id'), ['notification_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notification_reads_user_id'), ['user_id'], unique=False)

    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('actions', sa.JSON(), nullable=False),
    sa.Column('factors', sa.JSON(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['disaster_events.id'], name=op.f('fk_recommendations_event_id_disaster_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_recommendations_event_id'), ['event_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('relief_centers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('capacity_people', sa.Integer(), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], name=op.f('fk_relief_centers_district_id_geo_districts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relief_centers'))
    )
    op.create_table('water_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('district_id', sa.Integer(), nullable=True),
    sa.Column('capacity_litres_per_day', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('data_origin', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['geo_districts.id'], name=op.f('fk_water_sources_district_id_geo_districts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_sources'))
    )
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_anomalies_trip_id_trips')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['tankers.id'], name=op.f('fk_anomalies_vehicle_id_tankers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_anomalies_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomalies_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomalies_trip_id'), ['trip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_anomalies_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('telemetry',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.String(length=20), nullable=False),
    sa.Column('driver_user_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('speed_kmh', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('device_time', sa.DateTime(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('flags', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['driver_user_id'], ['users.id'], name=op.f('fk_telemetry_driver_user_id_users')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_telemetry_trip_id_trips')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['tankers.id'], name=op.f('fk_telemetry_vehicle_id_tankers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telemetry')),
    sa.UniqueConstraint('vehicle_id', 'device_time', name='uq_telemetry_vehicle_device_time')
    )
    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.create_index('ix_telemetry_trip_time', ['trip_id', 'device_time'], unique=False)
        batch_op.create_index('ix_telemetry_vehicle_time', ['vehicle_id', 'device_time'], unique=False)

    with op.batch_alter_table('gps_pings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gps_pings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_gps_pings_tanker_id'))

    op.drop_table('gps_pings')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('before', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('after', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('ip', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('user_agent', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('device_id', sa.String(length=80), nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_logs_entity_id'), ['entity_id'], unique=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False))
        batch_op.create_index(batch_op.f('ix_communities_district_id'), ['district_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_communities_state_id'), ['state_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_communities_state_id_geo_states'), 'geo_states', ['state_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_communities_district_id_geo_districts'), 'geo_districts', ['district_id'], ['id'])

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False))

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trip_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gps_device_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('receiver_phone', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verification_notes', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('signature_path', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_deliveries_trip_id'), ['trip_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_deliveries_trip_id_trips'), 'trips', ['trip_id'], ['id'])

    with op.batch_alter_table('depots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('district_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_litres', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stock_updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('capacity_litres', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_depots_district_id_geo_districts'), 'geo_districts', ['district_id'], ['id'])

    with op.batch_alter_table('tankers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_source', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('device_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('accuracy_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_device_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_source', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False))
        batch_op.alter_column('speed_kmh',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inside_streak', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('arrived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('arrival_distance_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('arrival_confirmed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delivered_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('origin_depot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dispatch_route_geometry', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('assigned_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('start_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('start_accuracy_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('arrived_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('driver_ended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancel_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('distance_travelled_km', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('deviation_streak', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('open_deviation_id', sa.Integer(), nullable=True))
        batch_op.alter_column('routing_source',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=24),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_trips_driver_user_id'), ['driver_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_trips_origin_depot_id_depots'), 'depots', ['origin_depot_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_trips_driver_user_id_users'), 'users', ['driver_user_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('water_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('fulfilled_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###
    # Data: renamed vocabularies
    op.execute("UPDATE tankers SET status = 'Available' WHERE status = 'Idle'")
    op.execute("UPDATE users SET role = 'operator' WHERE role = 'officer'")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_requests', schema=None) as batch_op:
        batch_op.drop_column('fulfilled_at')
        batch_op.drop_column('data_origin')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')
        batch_op.drop_column('must_change_password')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_trips_driver_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_trips_origin_depot_id_depots'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trips_driver_user_id'))
        batch_op.alter_column('routing_source',
               existing_type=sa.String(length=24),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
        batch_op.drop_column('open_deviation_id')
        batch_op.drop_column('deviation_streak')
        batch_op.drop_column('distance_travelled_km')
        batch_op.drop_column('cancel_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('driver_ended_at')
        batch_op.drop_column('arrived_at')
        batch_op.drop_column('start_accuracy_m')
        batch_op.drop_column('start_lng')
        batch_op.drop_column('start_lat')
        batch_op.drop_column('accepted_at')
        batch_op.drop_column('assigned_at')
        batch_op.drop_column('dispatch_route_geometry')
        batch_op.drop_column('origin_depot_id')
        batch_op.drop_column('driver_user_id')

    with op.batch_alter_table('trip_stops', schema=None) as batch_op:
        batch_op.drop_column('verified_at')
        batch_op.drop_column('delivered_at')
        batch_op.drop_column('arrival_confirmed_at')
        batch_op.drop_column('arrival_distance_m')
        batch_op.drop_column('arrived_at')
        batch_op.drop_column('inside_streak')

    with op.batch_alter_table('tankers', schema=None) as batch_op:
        batch_op.alter_column('speed_kmh',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('data_origin')
        batch_op.drop_column('last_source')
        batch_op.drop_column('last_device_time')
        batch_op.drop_column('accuracy_m')
        batch_op.drop_column('device_id')
        batch_op.drop_column('tracking_source')

    with op.batch_alter_table('depots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_depots_district_id_geo_districts'), type_='foreignkey')
        batch_op.drop_column('data_origin')
        batch_op.drop_column('capacity_litres')
        batch_op.drop_column('stock_updated_at')
        batch_op.drop_column('stock_litres')
        batch_op.drop_column('district_id')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_deliveries_trip_id_trips'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_deliveries_trip_id'))
        batch_op.drop_column('signature_path')
        batch_op.drop_column('verification_notes')
        batch_op.drop_column('verified_at')
        batch_op.drop_column('receiver_phone')
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('gps_device_time')
        batch_op.drop_column('trip_id')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_column('data_origin')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_communities_district_id_geo_districts'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_communities_state_id_geo_states'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_communities_state_id'))
        batch_op.drop_index(batch_op.f('ix_communities_district_id'))
        batch_op.drop_column('data_origin')
        batch_op.drop_column('district_id')
        batch_op.drop_column('state_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_entity_id'))
        batch_op.drop_column('device_id')
        batch_op.drop_column('user_agent')
        batch_op.drop_column('ip')
        batch_op.drop_column('after')
        batch_op.drop_column('before')
        batch_op.drop_column('user_role')

    op.create_table('gps_pings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('tanker_id', sa.VARCHAR(length=20), nullable=False),
    sa.Column('lat', sa.FLOAT(), nullable=False),
    sa.Column('lng', sa.FLOAT(), nullable=False),
    sa.Column('speed_kmh', sa.FLOAT(), nullable=False),
    sa.Column('heading', sa.FLOAT(), nullable=True),
    sa.Column('accuracy_m', sa.FLOAT(), nullable=True),
    sa.Column('recorded_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], name=op.f('fk_gps_pings_tanker_id_tankers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gps_pings'))
    )
    with op.batch_alter_table('gps_pings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gps_pings_tanker_id'), ['tanker_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gps_pings_recorded_at'), ['recorded_at'], unique=False)

    with op.batch_alter_table('telemetry', schema=None) as batch_op:
        batch_op.drop_index('ix_telemetry_vehicle_time')
        batch_op.drop_index('ix_telemetry_trip_time')

    op.drop_table('telemetry')
    with op.batch_alter_table('anomalies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomalies_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_anomalies_trip_id'))
        batch_op.drop_index(batch_op.f('ix_anomalies_kind'))
        batch_op.drop_index(batch_op.f('ix_anomalies_detected_at'))

    op.drop_table('anomalies')
    op.drop_table('water_sources')
    op.drop_table('relief_centers')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('recommendations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recommendations_event_id'))

    op.drop_table('recommendations')
    with op.batch_alter_table('notification_reads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_reads_user_id'))
        batch_op.drop_index(batch_op.f('ix_notification_reads_notification_id'))

    op.drop_table('notification_reads')
    with op.batch_alter_table('geo_districts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_districts_state_id'))
        batch_op.drop_index(batch_op.f('ix_geo_districts_name'))
        batch_op.drop_index(batch_op.f('ix_geo_districts_lgd_code'))

    op.drop_table('geo_districts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('ingestion_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_started_at'))
        batch_op.drop_index(batch_op.f('ix_ingestion_runs_source_key'))

    op.drop_table('ingestion_runs')
    with op.batch_alter_table('geo_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_states_name'))

    op.drop_table('geo_states')
    with op.batch_alter_table('disaster_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_disaster_events_source'))
        batch_op.drop_index(batch_op.f('ix_disaster_events_expires_at'))
        batch_op.drop_index(batch_op.f('ix_disaster_events_event_type'))

    op.drop_table('disaster_events')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
