"""maharashtra import crisis signals dispatch proposals

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-03 19:44:38.652846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crisis_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('publisher', sa.String(length=200), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('metric', sa.Float(), nullable=True),
    sa.Column('community_ids', sa.JSON(), nullable=False),
    sa.Column('district_ids', sa.JSON(), nullable=False),
    sa.Column('matched_terms', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=120), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crisis_signals')),
    sa.UniqueConstraint('external_id', name=op.f('uq_crisis_signals_external_id'))
    )
    with op.batch_alter_table('crisis_signals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crisis_signals_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crisis_signals_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_crisis_signals_published_at'), ['published_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crisis_signals_status'), ['status'], unique=False)

    op.create_table('dispatch_proposals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch', sa.String(length=32), nullable=False),
    sa.Column('tanker_id', sa.String(length=20), nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('community_ids', sa.JSON(), nullable=False),
    sa.Column('litres', sa.JSON(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('est_distance_km', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('auto', sa.Boolean(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], name=op.f('fk_dispatch_proposals_depot_id_depots')),
    sa.ForeignKeyConstraint(['tanker_id'], ['tankers.id'], name=op.f('fk_dispatch_proposals_tanker_id_tankers')),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], name=op.f('fk_dispatch_proposals_trip_id_trips')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dispatch_proposals'))
    )
    with op.batch_alter_table('dispatch_proposals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dispatch_proposals_batch'), ['batch'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_proposals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_proposals_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_dispatch_proposals_tanker_id'), ['tanker_id'], unique=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_supply', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('external_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('settlement_type', sa.String(length=16), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('source', sa.String(length=120), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('source_url', sa.String(length=500), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('demand_basis', sa.String(length=200), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('crisis_score', sa.Float(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('crisis_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_communities_external_id'), ['external_id'])

    with op.batch_alter_table('depots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_source_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('placement_note', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.create_foreign_key(batch_op.f('fk_depots_water_source_id_water_sources'), 'water_sources', ['water_source_id'], ['id'])

    with op.batch_alter_table('water_sources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_water_sources_external_id'), ['external_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_sources', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_water_sources_external_id'), type_='unique')
        batch_op.drop_column('external_id')

    with op.batch_alter_table('depots', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_depots_water_source_id_water_sources'), type_='foreignkey')
        batch_op.drop_column('is_active')
        batch_op.drop_column('placement_note')
        batch_op.drop_column('water_source_id')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_communities_external_id'), type_='unique')
        batch_op.drop_column('crisis_updated_at')
        batch_op.drop_column('crisis_score')
        batch_op.drop_column('demand_basis')
        batch_op.drop_column('source_url')
        batch_op.drop_column('source')
        batch_op.drop_column('settlement_type')
        batch_op.drop_column('external_id')
        batch_op.drop_column('baseline_supply')

    with op.batch_alter_table('dispatch_proposals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dispatch_proposals_tanker_id'))
        batch_op.drop_index(batch_op.f('ix_dispatch_proposals_status'))
        batch_op.drop_index(batch_op.f('ix_dispatch_proposals_created_at'))
        batch_op.drop_index(batch_op.f('ix_dispatch_proposals_batch'))

    op.drop_table('dispatch_proposals')
    with op.batch_alter_table('crisis_signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crisis_signals_status'))
        batch_op.drop_index(batch_op.f('ix_crisis_signals_published_at'))
        batch_op.drop_index(batch_op.f('ix_crisis_signals_kind'))
        batch_op.drop_index(batch_op.f('ix_crisis_signals_expires_at'))

    op.drop_table('crisis_signals')
    # ### end Alembic commands ###
