"""request dedupe, water access, tap schedules, offline complaints, synthetic history

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-03 23:44:15.645768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supply_notices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_supply_notices_community_id_communities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_supply_notices'))
    )
    with op.batch_alter_table('supply_notices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supply_notices_community_id'), ['community_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supply_notices_ends_at'), ['ends_at'], unique=False)

    op.create_table('tap_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('community_id', sa.String(length=40), nullable=False),
    sa.Column('point_name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('days', sa.JSON(), nullable=False),
    sa.Column('start_time', sa.String(length=5), nullable=False),
    sa.Column('end_time', sa.String(length=5), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data_origin', sa.String(length=16), nullable=False, server_default='manual'),
    sa.Column('updated_by', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['community_id'], ['communities.id'], name=op.f('fk_tap_schedules_community_id_communities')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tap_schedules'))
    )
    with op.batch_alter_table('tap_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tap_schedules_community_id'), ['community_id'], unique=False)

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('water_access_km', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('water_access_note', sa.String(length=200), nullable=False, server_default=''))

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=8), nullable=False, server_default='en'))
        batch_op.add_column(sa.Column('input_mode', sa.String(length=8), nullable=False, server_default='typed'))
        batch_op.add_column(sa.Column('client_ref', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('queued_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_complaints_client_ref'), ['client_ref'])

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False, server_default='manual'))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_origin', sa.String(length=16), nullable=False, server_default='manual'))

    with op.batch_alter_table('water_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duplicate_of_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('duplicate_reason', sa.String(length=300), nullable=False, server_default=''))
        batch_op.create_foreign_key(batch_op.f('fk_water_requests_duplicate_of_id_water_requests'), 'water_requests', ['duplicate_of_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('water_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_water_requests_duplicate_of_id_water_requests'), type_='foreignkey')
        batch_op.drop_column('duplicate_reason')
        batch_op.drop_column('duplicate_of_id')

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('data_origin')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_column('data_origin')

    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_complaints_client_ref'), type_='unique')
        batch_op.drop_column('queued_at')
        batch_op.drop_column('client_ref')
        batch_op.drop_column('input_mode')
        batch_op.drop_column('language')

    with op.batch_alter_table('communities', schema=None) as batch_op:
        batch_op.drop_column('water_access_note')
        batch_op.drop_column('water_access_km')

    with op.batch_alter_table('tap_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tap_schedules_community_id'))

    op.drop_table('tap_schedules')
    with op.batch_alter_table('supply_notices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supply_notices_ends_at'))
        batch_op.drop_index(batch_op.f('ix_supply_notices_community_id'))

    op.drop_table('supply_notices')
    # ### end Alembic commands ###
