"""Weather-driven water-demand forecasting.

The model predicts a *demand index*: the ratio of a community's daily water need to its
configured baseline daily demand.  Forecast litres = baseline x index.  Expressing the
target as an index lets one model serve communities of any size and makes the model
transferable as soon as real metered observations are recorded.

Training data
-------------
* Weather: real daily Open-Meteo reanalysis for Mumbai (2019-2025).
* Demand response: no public metered tanker-demand series exists for Mumbai, so the
  bootstrap target is generated by ``simulate_demand_index`` - an explicit, documented
  response function (heat, monsoon recharge, dry-season depletion, weekly cycle,
  autocorrelated noise).  ``train(db_url=...)`` mixes in real ``demand_observations``
  recorded by the backend; with enough real history the simulator can be dropped.

Model: gradient-boosted trees (median) + quantile models (P10/P90) for an 80% interval.
"""
from __future__ import annotations

import logging
import time
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error

from . import __version__, config
from .complaints import _write_metrics
from .weather import fetch_history

log = logging.getLogger(__name__)

FEATURES = [
    "temp_max", "temp_min", "precip", "humidity",
    "precip_3d", "precip_7d", "precip_30d", "temp_max_3d",
    "dow", "is_weekend", "doy_sin", "doy_cos", "month",
    "vulnerability_score",
]


def add_weather_features(weather: pd.DataFrame) -> pd.DataFrame:
    """Rolling/calendar features. ``weather`` must be sorted, contiguous daily rows."""
    w = weather.sort_values("date").reset_index(drop=True).copy()
    w["precip_3d"] = w["precip"].rolling(3, min_periods=1).sum()
    w["precip_7d"] = w["precip"].rolling(7, min_periods=1).sum()
    w["precip_30d"] = w["precip"].rolling(30, min_periods=1).sum()
    w["temp_max_3d"] = w["temp_max"].rolling(3, min_periods=1).mean()
    d = pd.to_datetime(w["date"])
    w["dow"] = d.dt.dayofweek
    w["is_weekend"] = (w["dow"] >= 5).astype(int)
    doy = d.dt.dayofyear
    w["doy_sin"] = np.sin(2 * np.pi * doy / 365.25)
    w["doy_cos"] = np.cos(2 * np.pi * doy / 365.25)
    w["month"] = d.dt.month
    return w


def simulate_demand_index(w: pd.DataFrame, vulnerability_score: float, rng: np.random.Generator) -> np.ndarray:
    """Documented bootstrap response function (see MODEL_CARD.md)."""
    v = vulnerability_score / 100.0
    heat = 1 + 0.035 * np.clip(w["temp_max"] - 30, 0, None) + 0.02 * np.clip(w["temp_max_3d"] - 33, 0, None)
    humidity = 1 - 0.0015 * (w["humidity"] - 70)
    # Monsoon recharge: sustained rain restores piped supply and wells, so tanker need falls.
    recharge = 1 - 0.28 * np.clip(w["precip_30d"] / 400.0, 0, 1) - 0.08 * np.clip(w["precip"] / 40.0, 0, 1)
    # Dry-season depletion (Mar-May) bites hardest in tanker-reliant settlements.
    dryness = w["month"].map({3: 1.0, 4: 1.0, 5: 1.0, 1: 0.4, 2: 0.6, 11: 0.2, 12: 0.3}).fillna(0.0)
    depletion = 1 + (0.06 + 0.12 * v) * dryness
    weekly = np.where(w["dow"] == 6, 1.06, np.where(w["dow"] == 5, 1.03, 1.0))

    noise = np.zeros(len(w))
    eps = rng.normal(0, 0.035, len(w))
    for i in range(1, len(w)):
        noise[i] = 0.6 * noise[i - 1] + eps[i]
    return np.clip(heat * humidity * recharge * depletion * weekly * (1 + noise), 0.4, 1.9)


def build_training_frame(weather: pd.DataFrame, n_archetypes: int = 12, seed: int = 3) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    w = add_weather_features(weather)
    frames = []
    for vuln in np.linspace(20, 98, n_archetypes):
        f = w.copy()
        f["vulnerability_score"] = round(float(vuln), 1)
        f["demand_index"] = simulate_demand_index(f, vuln, rng)
        frames.append(f)
    return pd.concat(frames, ignore_index=True)


def load_db_observations(db_url: str, weather: pd.DataFrame) -> pd.DataFrame:
    from sqlalchemy import create_engine, text

    engine = create_engine(db_url)
    with engine.connect() as conn:
        rows = conn.execute(text(
            "SELECT o.date AS date, o.litres AS litres, c.daily_demand AS baseline, c.vulnerability_score AS vulnerability_score "
            "FROM demand_observations o JOIN communities c ON c.id = o.community_id"
        )).mappings().all()
    if not rows:
        return pd.DataFrame()
    obs = pd.DataFrame(rows)
    obs["date"] = pd.to_datetime(obs["date"])
    obs["demand_index"] = obs["litres"] / obs["baseline"].clip(lower=1)
    feats = add_weather_features(weather)
    return obs.merge(feats, on="date", how="inner")[FEATURES + ["date", "demand_index"]]


def _fit(X: pd.DataFrame, y: pd.Series, loss: str, quantile: float | None = None, sample_weight=None):
    kwargs = {"loss": loss, "max_iter": 400, "learning_rate": 0.05, "max_leaf_nodes": 31, "min_samples_leaf": 40, "l2_regularization": 0.1, "random_state": 0}
    if quantile is not None:
        kwargs["quantile"] = quantile
    model = HistGradientBoostingRegressor(**kwargs)
    model.fit(X, y, sample_weight=sample_weight)
    return model


def train(db_url: str | None = None, out: Path | None = None, split_date: str = "2024-01-01") -> dict:
    config.ensure_dirs()
    out = out or config.DEMAND_MODEL_PATH
    t0 = time.time()

    weather = fetch_history()
    df = build_training_frame(weather)
    weights = np.ones(len(df))

    real = pd.DataFrame()
    if db_url:
        real = load_db_observations(db_url, weather)
        log.info("Loaded %d real demand observations", len(real))
        if len(real):
            df = pd.concat([df, real], ignore_index=True)
            weights = np.concatenate([weights, np.full(len(real), 10.0)])

    is_train = (pd.to_datetime(df["date"]) < split_date).to_numpy()
    X, y = df[FEATURES], df["demand_index"]

    # --- time-based evaluation --------------------------------------------------
    eval_model = _fit(X[is_train], y[is_train], "squared_error", sample_weight=weights[is_train])
    X_te, y_te = X[~is_train], y[~is_train]
    pred = eval_model.predict(X_te)
    month_mean = df[is_train].groupby("month")["demand_index"].mean()
    baseline_static = np.ones(len(y_te))
    baseline_seasonal = X_te["month"].map(month_mean).to_numpy()
    q10 = _fit(X[is_train], y[is_train], "quantile", 0.1, weights[is_train]).predict(X_te)
    q90 = _fit(X[is_train], y[is_train], "quantile", 0.9, weights[is_train]).predict(X_te)

    def m(p):
        return {"mae_index": round(float(mean_absolute_error(y_te, p)), 4), "mape_pct": round(100 * float(mean_absolute_percentage_error(y_te, p)), 2)}

    metrics = {
        "split": f"train < {split_date} <= test",
        "n_train": int(is_train.sum()),
        "n_test": int((~is_train).sum()),
        "model": m(pred),
        "baseline_static_demand": m(baseline_static),
        "baseline_monthly_seasonal": m(baseline_seasonal),
        "interval_80_coverage_pct": round(100 * float(np.mean((y_te >= q10) & (y_te <= q90))), 1),
        "n_real_observations": int(len(real)),
    }

    # --- final models on all data ----------------------------------------------
    bundle = {
        "median": _fit(X, y, "squared_error", sample_weight=weights),
        "p10": _fit(X, y, "quantile", 0.1, weights),
        "p90": _fit(X, y, "quantile", 0.9, weights),
        "features": FEATURES,
        "meta": {
            "model": "HistGradientBoosting (median + P10/P90 quantile)",
            "target": "demand_index = daily demand / community baseline",
            "weather_source": "Open-Meteo archive (ERA5 reanalysis), Mumbai",
            "weather_range": [str(weather["date"].min().date()), str(weather["date"].max().date())],
            "version": __version__,
            "trained_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "train_seconds": round(time.time() - t0, 1),
        },
        "metrics": metrics,
    }
    joblib.dump(bundle, out, compress=3)
    _write_metrics("demand_forecaster", {"meta": bundle["meta"], "metrics": metrics})
    return bundle


class DemandForecaster:
    def __init__(self, path: Path | None = None):
        path = path or config.DEMAND_MODEL_PATH
        if not Path(path).exists():
            raise FileNotFoundError(f"Demand model not found at {path}. Run `python -m jalsetu_ml.train demand`.")
        b = joblib.load(path)
        self.median, self.p10, self.p90 = b["median"], b["p10"], b["p90"]
        self.features = b["features"]
        self.meta, self.metrics = b["meta"], b["metrics"]

    def forecast(self, weather: pd.DataFrame, baseline_litres: float, vulnerability_score: float, start_date=None) -> list[dict]:
        """``weather`` should include ~30 past days (for rolling rain) plus the forecast horizon."""
        f = add_weather_features(weather)
        f["vulnerability_score"] = vulnerability_score
        if start_date is not None:
            f = f[pd.to_datetime(f["date"]) >= pd.Timestamp(start_date)]
        X = f[self.features]
        mid = self.median.predict(X)
        lo = np.minimum(self.p10.predict(X), mid)
        hi = np.maximum(self.p90.predict(X), mid)
        out = []
        for (_, row), a, b, c in zip(f.iterrows(), lo, mid, hi):
            out.append({
                "date": pd.Timestamp(row["date"]).date().isoformat(),
                "demand_index": round(float(b), 3),
                "litres_p10": int(round(baseline_litres * a, -2)),
                "litres_p50": int(round(baseline_litres * b, -2)),
                "litres_p90": int(round(baseline_litres * c, -2)),
                "temp_max": round(float(row["temp_max"]), 1),
                "precip_mm": round(float(row["precip"]), 1),
            })
        return out
